[
    {
      
        "DataDeCriacao": "28/01/2021 22:12:37",
        "DataDeEntrega": null,
        "Cliente": "CNPJ",
        "FormaDePagamento": "BOLETO",
        "CondicaoDePagamento": "30/60/90 D",
        "ItensPedidos": [
            {
                "Produto": "CODIGOPRODUTO",
                "Quantidade": "1,0000000000",
                "PrecoUnitario": "144,70",
                "ValorTotal": "144,70"
            },
            {
                "Produto": "PROTETOR TRADICIONAL COMPAT. C/ TITAN 150 04/09/14 FAN 150 09/14 CG START 160/16",
                "Quantidade": "2,0000000000",
                "PrecoUnitario": "R$ 36,53",
                "ValorTotal": "R$ 73,06"
            },
            {
                "Produto": "CAVALETE CENTRAL COMPATIVEL C/ TITAN 160 2016",
                "Quantidade": "2,0000000000",
                "PrecoUnitario": "R$ 34,99",
                "ValorTotal": "R$ 69,98"
            },
            {
                "Produto": "ESCAPE MOD. PRO TORK COMPETITION COMPAT. C/ POP 110 2016 (PRETO)",
                "Quantidade": "1,0000000000",
                "PrecoUnitario": "R$ 93,65",
                "ValorTotal": "R$ 93,65"
            },
            {
                "Produto": "PROTETOR TRADICIONAL COMPATIVEL C/ CROSSER XTZ 150",
                "Quantidade": "5,0000000000",
                "PrecoUnitario": "R$ 36,68",
                "ValorTotal": "R$ 183,40"
            },
            {
                "Produto": "ALCA MOD. ARROW COMPT. C/ TITAN 150 14-FAN 125/150 14-FAN 160/16-CG START 150/14 E 160/16-FAN 125/17",
                "Quantidade": "2,0000000000",
                "PrecoUnitario": "R$ 35,01",
                "ValorTotal": "R$ 70,02"
            },
            {
                "Produto": "ESCAPE MOD. PRO TORK COMPETITION COMPAT. C/ TITAN 160 (PRETO)",
                "Quantidade": "1,0000000000",
                "PrecoUnitario": "R$ 93,65",
                "ValorTotal": "R$ 93,65"
            },
            {
                "Produto": "ESCAPE MOD. PRO TORK COMPETITION COMPAT. C/ POP 110 2016 (PRETO)",
                "Quantidade": "1,0000000000",
                "PrecoUnitario": "R$ 93,65",
                "ValorTotal": "R$ 93,65"
            },
            {
                "Produto": "KIT BOTAO DO CAPACETE SPORT MOTO",
                "Quantidade": "10,0000000000",
                "PrecoUnitario": "R$ 8,37",
                "ValorTotal": "R$ 83,70"
            },
            {
                "Produto": "PROTETOR DE CORRENTE COMPAT. C/ FAZER 150 2014",
                "Quantidade": "2,0000000000",
                "PrecoUnitario": "R$ 54,21",
                "ValorTotal": "R$ 108,42"
            },
            {
                "Produto": "ESCAPE MOD. PRO TORK COMPETITION COMPAT. C/ POP 100 (PRETO)",
                "Quantidade": "1,0000000000",
                "PrecoUnitario": "R$ 93,65",
                "ValorTotal": "R$ 93,65"
            },
            {
                "Produto": "ESCAPE MOD. PRO TORK COMPETITION COMPAT. C/ POP 110 2016 (PRETO)",
                "Quantidade": "1,0000000000",
                "PrecoUnitario": "R$ 93,65",
                "ValorTotal": "R$ 93,65"
            },
            {
                "Produto": "PORTA CAPACETE COMPAT. C/ BIZ 125 KS/ES/+ EX 2011 A 2017 / BIZ 100 KS/ES 2012/2013",
                "Quantidade": "1,0000000000",
                "PrecoUnitario": "R$ 42,14",
                "ValorTotal": "R$ 42,14"
            },
            {
                "Produto": "VISEIRA CAP. LIBERTY FOUR 2,0MM",
                "Quantidade": "2,0000000000",
                "PrecoUnitario": "R$ 15,39",
                "ValorTotal": "R$ 30,78"
            },
            {
                "Produto": "CAVALETE CENTRAL COMPAT. C/ FAZER 150 / FACTOR 150 2018 (COM PINO E MOLA)",
                "Quantidade": "2,0000000000",
                "PrecoUnitario": "R$ 32,85",
                "ValorTotal": "R$ 65,70"
            },
            {
                "Produto": "RABETA COMPATIVEL COM BROSS 2009/14 (PARTE DE CIMA DO BAGAGEIRO)",
                "Quantidade": "2,0000000000",
                "PrecoUnitario": "R$ 28,71",
                "ValorTotal": "R$ 57,42"
            },
            {
                "Produto": "CAPACETE EVOLUTION G8 EVO BRILHANTE TAM.60",
                "Quantidade": "1,0000000000",
                "PrecoUnitario": "R$ 234,86",
                "ValorTotal": "R$ 234,86"
            },
            {
                "Produto": "ALCA MOD. ARROW COMPT. C/ TITAN 150 14-FAN 125/150 14-FAN 160/16-CG START 150/14 E 160/16-FAN 125/17",
                "Quantidade": "6,0000000000",
                "PrecoUnitario": "R$ 35,01",
                "ValorTotal": "R$ 210,06"
            },
            {
                "Produto": "MASCARA DO CAPACETE SPORT MOTO",
                "Quantidade": "20,0000000000",
                "PrecoUnitario": "R$ 12,07",
                "ValorTotal": "R$ 241,40"
            },
            {
                "Produto": "CAPACETE EVOLUTION G8 EVO BRILHANTE TAM.60",
                "Quantidade": "1,0000000000",
                "PrecoUnitario": "R$ 234,86",
                "ValorTotal": "R$ 234,86"
            },
            {
                "Produto": "ESCAPE MOD. PRO TORK COMPETITION COMPAT. C/ TITAN 160 (PRETO)",
                "Quantidade": "1,0000000000",
                "PrecoUnitario": "R$ 93,65",
                "ValorTotal": "R$ 93,65"
            },
            {
                "Produto": "VISEIRA CAP. EVOLUTION 2,0 MM (INJETADA)",
                "Quantidade": "2,0000000000",
                "PrecoUnitario": "R$ 27,50",
                "ValorTotal": "R$ 55,00"
            },
            {
                "Produto": "PROTETOR TRADICIONAL COMPATIVEL C/ TITAN 160 2016 A 19/FAN 160",
                "Quantidade": "4,0000000000",
                "PrecoUnitario": "R$ 36,68",
                "ValorTotal": "R$ 146,72"
            },
            {
                "Produto": "ESCAPE MOD. PRO TORK COMPETITION COMPAT. C/ TITAN 160 (PRETO)",
                "Quantidade": "1,0000000000",
                "PrecoUnitario": "R$ 93,65",
                "ValorTotal": "R$ 93,65"
            },
            {
                "Produto": "ESCAPE MOD. PRO TORK COMPETITION COMPAT. C/ POP 100 (PRETO)",
                "Quantidade": "1,0000000000",
                "PrecoUnitario": "R$ 93,65",
                "ValorTotal": "R$ 93,65"
            },
            {
                "Produto": "PROTETOR TRADICIONAL COMPAT. C/ TITAN 150 04/09/14 FAN 150 09/14 CG START 160/16",
                "Quantidade": "5,0000000000",
                "PrecoUnitario": "R$ 36,53",
                "ValorTotal": "R$ 182,65"
            },
            {
                "Produto": "PROTETOR TRADICIONAL COMPATIVEL C/ TITAN 160 2016 A 19",
                "Quantidade": "10,0000000000",
                "PrecoUnitario": "R$ 36,68",
                "ValorTotal": "R$ 366,80"
            },
            {
                "Produto": "CAPACETE R8 PRO TORK FUNDO PRETO TAM.58 VIS. ESPELHADA",
                "Quantidade": "1,0000000000",
                "PrecoUnitario": "R$ 144,70",
                "ValorTotal": "R$ 144,70"
            }
        ]
    }
]